Repository rust-amplify/rust-amplify, pull requests merged in 2020-10, with the labels that each got.

#10 Move serde string deser helper to a separate crate
  .gitignore
  Cargo.lock
  Cargo.toml
  serde_str_helpers/Cargo.toml
  serde_str_helpers/README.md
  serde_str_helpers/src/lib.rs
Labels: enhancement

#12 Fix missed export service::Exec type
  src/lib.rs
Labels: bug

#8 Add support for 1.41.1 rust compiler
  .github/workflows/features.yml
  Cargo.lock
  Cargo.toml
  README.md
  derive/Cargo.toml
  src/internet.rs
Labels: enhancement

#18 Prepare for publishing stringly_conversions
  stringly_conversions/Cargo.toml
Labels: enhancement

#21 Making `InetAddr` `Copy`
  Cargo.lock
  Cargo.toml
  src/internet.rs
Labels: enhancement

#22 Convenience functions for extracting Tor addresses
  .github/workflows/build.yml
  src/internet.rs
Labels: enhancement

#25 v2.0 release
  .github/workflows/build.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  derive/CHANGELOG.md
  derive/Cargo.toml
  derive/README.md
  derive/src/display.rs
  derive/src/from.rs
  derive/src/lib.rs
  derive/src/wrapper.rs
  src/convert.rs
  src/internet.rs
  src/lib.rs
  src/serde_helpers.rs
  src/service.rs
  src/wrapper.rs
Labels: documentation, enhancement
